version: "3"

networks:
  default:
    external:
      name: docker-dev

services:

  sandbox-dev:
    command: yarn develop
    image: kedge/gatsby-dev
    volumes:
    - ./:/site
    working_dir: /site
    ports:
    - "80"
    environment:
      VIRTUAL_HOST: gatsby.local
    networks:
      default:
        aliases:
        - gatsby.local
